name: Lambda Deploy

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: your-lambda-function-name
      REGION: ap-northeast-1  # 適宜変更

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Zip Lambda function (dev only)
        if: github.ref == 'refs/heads/dev'
        run: |
          zip -r lambda_function.zip .

      - name: Deploy to Lambda (dev only)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda_function.zip \
            --publish > output.json
          VERSION=$(jq -r '.Version' output.json)
          echo "New version: $VERSION"
          aws lambda update-alias \
            --function-name $FUNCTION_NAME \
            --name dev \
            --function-version $VERSION

      - name: Update prod alias (prod only)
        if: github.ref == 'refs/heads/prod'
        run: |
          LATEST_VERSION=$(aws lambda list-versions-by-function \
            --function-name $FUNCTION_NAME \
            --query 'Versions[?Version!=`$LATEST`]|[-1].Version' \
            --output text)
          echo "Updating prod alias to version $LATEST_VERSION"
          aws lambda update-alias \
            --function-name $FUNCTION_NAME \
            --name prod \
            --function-version $LATEST_VERSION
